[package]
authors = ["phiresky <phireskyde+git@gmail.com>"]
name = "rust"
version = "0.1.0"

[dependencies]
csv = "1.0.0-beta.5"
serde_derive = "1.0.27"
serde = "1.0.27"
prost = "0.2.3"
prost-derive = "0.2.3"
bytes = "0.4.6"
serde_json = "1.0.9"

[build-dependencies]
prost-build = "0.2.3"
